// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: agents.proto

package hub_agent_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewAgentResponse_AgentState int32

const (
	NewAgentResponse_ACK              NewAgentResponse_AgentState = 0
	NewAgentResponse_ALREADY_EXISTS   NewAgentResponse_AgentState = 1
	NewAgentResponse_CONNECTION_ISSUE NewAgentResponse_AgentState = 2
)

// Enum value maps for NewAgentResponse_AgentState.
var (
	NewAgentResponse_AgentState_name = map[int32]string{
		0: "ACK",
		1: "ALREADY_EXISTS",
		2: "CONNECTION_ISSUE",
	}
	NewAgentResponse_AgentState_value = map[string]int32{
		"ACK":              0,
		"ALREADY_EXISTS":   1,
		"CONNECTION_ISSUE": 2,
	}
)

func (x NewAgentResponse_AgentState) Enum() *NewAgentResponse_AgentState {
	p := new(NewAgentResponse_AgentState)
	*p = x
	return p
}

func (x NewAgentResponse_AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NewAgentResponse_AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_agents_proto_enumTypes[0].Descriptor()
}

func (NewAgentResponse_AgentState) Type() protoreflect.EnumType {
	return &file_agents_proto_enumTypes[0]
}

func (x NewAgentResponse_AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NewAgentResponse_AgentState.Descriptor instead.
func (NewAgentResponse_AgentState) EnumDescriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{4, 0}
}

type TcpConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *TcpConnection) Reset() {
	*x = TcpConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpConnection) ProtoMessage() {}

func (x *TcpConnection) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpConnection.ProtoReflect.Descriptor instead.
func (*TcpConnection) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{0}
}

func (x *TcpConnection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TcpConnection) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RpcConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RpcConnection) Reset() {
	*x = RpcConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcConnection) ProtoMessage() {}

func (x *RpcConnection) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcConnection.ProtoReflect.Descriptor instead.
func (*RpcConnection) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{1}
}

func (x *RpcConnection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RpcConnection) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Connection:
	//	*Agent_Tcp
	//	*Agent_Rpc
	Connection  isAgent_Connection `protobuf_oneof:"connection"`
	DisplayName string             `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{2}
}

func (m *Agent) GetConnection() isAgent_Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (x *Agent) GetTcp() *TcpConnection {
	if x, ok := x.GetConnection().(*Agent_Tcp); ok {
		return x.Tcp
	}
	return nil
}

func (x *Agent) GetRpc() *RpcConnection {
	if x, ok := x.GetConnection().(*Agent_Rpc); ok {
		return x.Rpc
	}
	return nil
}

func (x *Agent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type isAgent_Connection interface {
	isAgent_Connection()
}

type Agent_Tcp struct {
	Tcp *TcpConnection `protobuf:"bytes,1,opt,name=tcp,proto3,oneof"`
}

type Agent_Rpc struct {
	Rpc *RpcConnection `protobuf:"bytes,2,opt,name=rpc,proto3,oneof"`
}

func (*Agent_Tcp) isAgent_Connection() {}

func (*Agent_Rpc) isAgent_Connection() {}

type NewAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent *Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *NewAgentRequest) Reset() {
	*x = NewAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAgentRequest) ProtoMessage() {}

func (x *NewAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAgentRequest.ProtoReflect.Descriptor instead.
func (*NewAgentRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{3}
}

func (x *NewAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type NewAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentState            NewAgentResponse_AgentState `protobuf:"varint,1,opt,name=agent_state,json=agentState,proto3,enum=hub_protos.agents.NewAgentResponse_AgentState" json:"agent_state,omitempty"`
	NextKeepaliveDeadline uint64                      `protobuf:"varint,2,opt,name=next_keepalive_deadline,json=nextKeepaliveDeadline,proto3" json:"next_keepalive_deadline,omitempty"`
	Guid                  []byte                      `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *NewAgentResponse) Reset() {
	*x = NewAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAgentResponse) ProtoMessage() {}

func (x *NewAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAgentResponse.ProtoReflect.Descriptor instead.
func (*NewAgentResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{4}
}

func (x *NewAgentResponse) GetAgentState() NewAgentResponse_AgentState {
	if x != nil {
		return x.AgentState
	}
	return NewAgentResponse_ACK
}

func (x *NewAgentResponse) GetNextKeepaliveDeadline() uint64 {
	if x != nil {
		return x.NextKeepaliveDeadline
	}
	return 0
}

func (x *NewAgentResponse) GetGuid() []byte {
	if x != nil {
		return x.Guid
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disconnect bool   `protobuf:"varint,1,opt,name=disconnect,proto3" json:"disconnect,omitempty"`
	Guid       []byte `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetDisconnect() bool {
	if x != nil {
		return x.Disconnect
	}
	return false
}

func (x *PingRequest) GetGuid() []byte {
	if x != nil {
		return x.Guid
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextKeepaliveDeadline uint64 `protobuf:"varint,1,opt,name=next_keepalive_deadline,json=nextKeepaliveDeadline,proto3" json:"next_keepalive_deadline,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetNextKeepaliveDeadline() uint64 {
	if x != nil {
		return x.NextKeepaliveDeadline
	}
	return 0
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login   string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Columns uint32 `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	Rows    uint32 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{7}
}

func (x *Login) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Login) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Login) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buf []byte `protobuf:"bytes,1,opt,name=buf,proto3" json:"buf,omitempty"`
}

func (x *Read) Reset() {
	*x = Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{8}
}

func (x *Read) GetBuf() []byte {
	if x != nil {
		return x.Buf
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns uint32 `protobuf:"varint,1,opt,name=columns,proto3" json:"columns,omitempty"`
	Rows    uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *Resize) Reset() {
	*x = Resize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{9}
}

func (x *Resize) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Disconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{10}
}

type AgentStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Frame:
	//	*AgentStreamRequest_Login
	//	*AgentStreamRequest_Read
	//	*AgentStreamRequest_Resize
	//	*AgentStreamRequest_Disconnect
	Frame isAgentStreamRequest_Frame `protobuf_oneof:"frame"`
}

func (x *AgentStreamRequest) Reset() {
	*x = AgentStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamRequest) ProtoMessage() {}

func (x *AgentStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamRequest.ProtoReflect.Descriptor instead.
func (*AgentStreamRequest) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{11}
}

func (m *AgentStreamRequest) GetFrame() isAgentStreamRequest_Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (x *AgentStreamRequest) GetLogin() *Login {
	if x, ok := x.GetFrame().(*AgentStreamRequest_Login); ok {
		return x.Login
	}
	return nil
}

func (x *AgentStreamRequest) GetRead() *Read {
	if x, ok := x.GetFrame().(*AgentStreamRequest_Read); ok {
		return x.Read
	}
	return nil
}

func (x *AgentStreamRequest) GetResize() *Resize {
	if x, ok := x.GetFrame().(*AgentStreamRequest_Resize); ok {
		return x.Resize
	}
	return nil
}

func (x *AgentStreamRequest) GetDisconnect() *Disconnect {
	if x, ok := x.GetFrame().(*AgentStreamRequest_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

type isAgentStreamRequest_Frame interface {
	isAgentStreamRequest_Frame()
}

type AgentStreamRequest_Login struct {
	Login *Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type AgentStreamRequest_Read struct {
	Read *Read `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type AgentStreamRequest_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type AgentStreamRequest_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,4,opt,name=disconnect,proto3,oneof"`
}

func (*AgentStreamRequest_Login) isAgentStreamRequest_Frame() {}

func (*AgentStreamRequest_Read) isAgentStreamRequest_Frame() {}

func (*AgentStreamRequest_Resize) isAgentStreamRequest_Frame() {}

func (*AgentStreamRequest_Disconnect) isAgentStreamRequest_Frame() {}

type Write struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buf []byte `protobuf:"bytes,1,opt,name=buf,proto3" json:"buf,omitempty"`
}

func (x *Write) Reset() {
	*x = Write{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{12}
}

func (x *Write) GetBuf() []byte {
	if x != nil {
		return x.Buf
	}
	return nil
}

type AgentStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Write *Write `protobuf:"bytes,1,opt,name=write,proto3" json:"write,omitempty"`
}

func (x *AgentStreamResponse) Reset() {
	*x = AgentStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agents_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamResponse) ProtoMessage() {}

func (x *AgentStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agents_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamResponse.ProtoReflect.Descriptor instead.
func (*AgentStreamResponse) Descriptor() ([]byte, []int) {
	return file_agents_proto_rawDescGZIP(), []int{13}
}

func (x *AgentStreamResponse) GetWrite() *Write {
	if x != nil {
		return x.Write
	}
	return nil
}

var File_agents_proto protoreflect.FileDescriptor

var file_agents_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x37, 0x0a, 0x0d, 0x54, 0x63, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x37, 0x0a, 0x0d, 0x52, 0x70,
	0x63, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a,
	0x03, 0x74, 0x63, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x68, 0x75, 0x62,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x54,
	0x63, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03,
	0x74, 0x63, 0x70, 0x12, 0x34, 0x0a, 0x03, 0x72, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x72, 0x70, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x0f, 0x4e, 0x65,
	0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a,
	0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68,
	0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xf0, 0x01,
	0x0a, 0x10, 0x4e, 0x65, 0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x6e, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c,
	0x69, 0x76, 0x65, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x22,
	0x3f, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x43, 0x4b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f,
	0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x53, 0x53, 0x55, 0x45, 0x10, 0x02,
	0x22, 0x41, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6b, 0x65, 0x65, 0x70,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x6e, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c,
	0x69, 0x76, 0x65, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x4b, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x18, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x62,
	0x75, 0x66, 0x22, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0xf4, 0x01, 0x0a, 0x12, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64,
	0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x75, 0x62, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22,
	0x19, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x62, 0x75, 0x66, 0x22, 0x45, 0x0a, 0x13, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x05, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x32, 0xaf, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x73,
	0x12, 0x53, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x68,
	0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x4e, 0x65, 0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x70, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x73, 0x12, 0x60, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x25, 0x2e, 0x68, 0x75, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x68, 0x75, 0x62, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agents_proto_rawDescOnce sync.Once
	file_agents_proto_rawDescData = file_agents_proto_rawDesc
)

func file_agents_proto_rawDescGZIP() []byte {
	file_agents_proto_rawDescOnce.Do(func() {
		file_agents_proto_rawDescData = protoimpl.X.CompressGZIP(file_agents_proto_rawDescData)
	})
	return file_agents_proto_rawDescData
}

var file_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agents_proto_goTypes = []interface{}{
	(NewAgentResponse_AgentState)(0), // 0: hub_protos.agents.NewAgentResponse.AgentState
	(*TcpConnection)(nil),            // 1: hub_protos.agents.TcpConnection
	(*RpcConnection)(nil),            // 2: hub_protos.agents.RpcConnection
	(*Agent)(nil),                    // 3: hub_protos.agents.Agent
	(*NewAgentRequest)(nil),          // 4: hub_protos.agents.NewAgentRequest
	(*NewAgentResponse)(nil),         // 5: hub_protos.agents.NewAgentResponse
	(*PingRequest)(nil),              // 6: hub_protos.agents.PingRequest
	(*PingResponse)(nil),             // 7: hub_protos.agents.PingResponse
	(*Login)(nil),                    // 8: hub_protos.agents.Login
	(*Read)(nil),                     // 9: hub_protos.agents.Read
	(*Resize)(nil),                   // 10: hub_protos.agents.Resize
	(*Disconnect)(nil),               // 11: hub_protos.agents.Disconnect
	(*AgentStreamRequest)(nil),       // 12: hub_protos.agents.AgentStreamRequest
	(*Write)(nil),                    // 13: hub_protos.agents.Write
	(*AgentStreamResponse)(nil),      // 14: hub_protos.agents.AgentStreamResponse
}
var file_agents_proto_depIdxs = []int32{
	1,  // 0: hub_protos.agents.Agent.tcp:type_name -> hub_protos.agents.TcpConnection
	2,  // 1: hub_protos.agents.Agent.rpc:type_name -> hub_protos.agents.RpcConnection
	3,  // 2: hub_protos.agents.NewAgentRequest.agent:type_name -> hub_protos.agents.Agent
	0,  // 3: hub_protos.agents.NewAgentResponse.agent_state:type_name -> hub_protos.agents.NewAgentResponse.AgentState
	8,  // 4: hub_protos.agents.AgentStreamRequest.login:type_name -> hub_protos.agents.Login
	9,  // 5: hub_protos.agents.AgentStreamRequest.read:type_name -> hub_protos.agents.Read
	10, // 6: hub_protos.agents.AgentStreamRequest.resize:type_name -> hub_protos.agents.Resize
	11, // 7: hub_protos.agents.AgentStreamRequest.disconnect:type_name -> hub_protos.agents.Disconnect
	13, // 8: hub_protos.agents.AgentStreamResponse.write:type_name -> hub_protos.agents.Write
	4,  // 9: hub_protos.agents.AgentComms.NewAgent:input_type -> hub_protos.agents.NewAgentRequest
	6,  // 10: hub_protos.agents.AgentComms.PingAgent:input_type -> hub_protos.agents.PingRequest
	12, // 11: hub_protos.agents.AgentStreams.AgentStream:input_type -> hub_protos.agents.AgentStreamRequest
	5,  // 12: hub_protos.agents.AgentComms.NewAgent:output_type -> hub_protos.agents.NewAgentResponse
	7,  // 13: hub_protos.agents.AgentComms.PingAgent:output_type -> hub_protos.agents.PingResponse
	14, // 14: hub_protos.agents.AgentStreams.AgentStream:output_type -> hub_protos.agents.AgentStreamResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_agents_proto_init() }
func file_agents_proto_init() {
	if File_agents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcpConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Write); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agents_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_agents_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Agent_Tcp)(nil),
		(*Agent_Rpc)(nil),
	}
	file_agents_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*AgentStreamRequest_Login)(nil),
		(*AgentStreamRequest_Read)(nil),
		(*AgentStreamRequest_Resize)(nil),
		(*AgentStreamRequest_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agents_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agents_proto_goTypes,
		DependencyIndexes: file_agents_proto_depIdxs,
		EnumInfos:         file_agents_proto_enumTypes,
		MessageInfos:      file_agents_proto_msgTypes,
	}.Build()
	File_agents_proto = out.File
	file_agents_proto_rawDesc = nil
	file_agents_proto_goTypes = nil
	file_agents_proto_depIdxs = nil
}
